version: '3'
services:
  cobra-cli:
    build: .
    volumes:
      - .:/app

  database:
    build:
      context: ./docker/database
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./docker/database/mysql:/var/lib/mysql
      - ./docker/database/initdb.d:/docker-entrypoint-initdb.d
